### PR TITLE
Updated to 1.15.2 and bumped mod version up by a minor

### PR DESCRIPTION
**Pull request by bernie-g**
Should probably make a new branch
Also please upload to the curseforge maven server :)

### CODE REVIEW

**Comment by MrCrayfish** [comment]
GlStateManager is deprecated in 1.15 and should be using RenderSystem

**Comment by bernie-g** [comment]
I guess, but the mod still works fine. I'll try to replace it later.

**Comment by bernie-g** [comment]
Alright I fixed it. I left a couple calls to the constants in the GLStateManager.SourceFactor class as they are just integers and not deprecated/don't have an equivalent in RenderSystem that I could find.

**Comment by bernie-g** [comment]
Any updates on this?

**Comment by Ocelot5836** [comment]
👍

**Pull request merged**
